"""add Admin

Revision ID: 723c4b549a3e
Revises: ae1ef4126679
Create Date: 2024-11-25 11:36:40.355889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723c4b549a3e'
down_revision = 'ae1ef4126679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('power', sa.String(length=80), nullable=False),
    sa.Column('person', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    # ### end Alembic commands ###
